# Generated by Django 4.2.9 on 2026-05-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadNonInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_non_interesse', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Lead Non Interested',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_status', models.CharField(choices=[('to_contact', 'To contact'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('lost', 'Lost')], default='to_contact', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_interesse', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Lead Interested',
                'ordering': ['-created_at'],
            },
        ),
    ]
